spin_manifest_version = 2

[application]
name = "doormat"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "doormat"

[component.doormat]
source = "target/wasm32-wasip1/release/doormat.wasm"
allowed_outbound_hosts = []

[component.doormat.build]
command = "cargo build --target wasm32-wasip1 --release"

[component.doormat.spin-test]
source = "target/wasm32-wasip1/release/tests.wasm"
build = "cargo component build --release"
workdir = "tests"
